export const States = {

    MAIN: "MAIN",

    SUPPORT: "SUPPORT",

    WAIT_SUPPORT_MESSAGE: "WAIT_SUPPORT_MESSAGE",

    ADMIN: "ADMIN",

    ADMIN_ADD_CONFIG: "ADMIN_ADD_CONFIG",

    ADMIN_REPLY: "ADMIN_REPLY",

    ADMIN_REPLY_SUPPORT: "ADMIN_REPLY_SUPPORT",
}